name: Terraform IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: curl -s https://tfsec.dev/install.sh | bash

      - name: Run tfsec
        run: tfsec ./terraform
