name: Terraform IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec scan via Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src aquasec/tfsec /src/aws-engineering-assessment/terraform
