name: Terraform IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src aquasec/tfsec /src/terraform

      # 3. Run tfsec scan on terraform/ folder
      - name: Run tfsec
        run: tfsec ./aws-engineering-assessment/terraform
