name: Terraform IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tfsec and save JSON report
        run: |
          docker run --rm -v ${{ github.workspace }}:/src aquasec/tfsec /src/aws-engineering-assessment/terraform --format json --soft-fail > tfsec-report.json

      - name: Upload tfsec report
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: tfsec-report.json
