name: Terraform IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install tfsec
      - name: Install tfsec
        run: curl -s https://tfsec.dev/install.sh | bash

      # 3. Run tfsec scan on terraform/ folder
      - name: Run tfsec
        run: tfsec ./terraform
