name: Terraform IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          TFSEC_VERSION="1.32.2"  # pick latest release
          curl -L https://github.com/aquasecurity/tfsec/releases/download/v$TFSEC_VERSION/tfsec-linux-amd64 -o /usr/local/bin/tfsec
          chmod +x /usr/local/bin/tfsec

      # 3. Run tfsec scan on terraform/ folder
      - name: Run tfsec
        run: tfsec ./aws-engineering-assessment/terraform
